using System;
using System.Windows.Forms;
using System.Drawing;
namespace FluentWinForms
{
    partial class Form1
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        ///  Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            modernFormManager1 = new FluentWinForms.Core.ModernFormManager(components);
            modernThemeToggle1 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle2 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle3 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle4 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle5 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle6 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle7 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle8 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle9 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle10 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle11 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle12 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle13 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle14 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle15 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle16 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle17 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle18 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle19 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            modernThemeToggle20 = new FluentWinForms.Custom_Buttons.ModernThemeToggle();
            SuspendLayout();
            // 
            // modernFormManager1
            // 
            modernFormManager1.AutoSetBlackBackground = true;
            modernFormManager1.BackdropType = Core.FormBackdropType.Acrylic;
            modernFormManager1.BorderColor = Color.FromArgb(40, 255, 255, 255);
            modernFormManager1.BorderRadius = 14;
            modernFormManager1.BorderThickness = 0F;
            modernFormManager1.DragControl = null;
            modernFormManager1.DragOpacity = 1D;
            modernFormManager1.EnableDrag = true;
            modernFormManager1.ForceDarkModeTitleBar = true;
            modernFormManager1.TargetForm = this;
            modernFormManager1.TransparentStyle = false;
            modernFormManager1.UseModernRoundedCorners = true;
            modernFormManager1.UseSkia = true;
            // 
            // modernThemeToggle1
            // 
            modernThemeToggle1.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle1.AnimationSpeed = 150F;
            modernThemeToggle1.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle1.BackColor = Color.Transparent;
            modernThemeToggle1.BackgroundColor = Color.Transparent;
            modernThemeToggle1.BackgroundColor2 = Color.Transparent;
            modernThemeToggle1.BackgroundImg = null;
            modernThemeToggle1.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle1.BorderColor = Color.Transparent;
            modernThemeToggle1.BorderRadius = 14F;
            modernThemeToggle1.BorderThickness = 0F;
            modernThemeToggle1.CheckedColor = Color.Transparent;
            modernThemeToggle1.CheckedColor2 = Color.Transparent;
            modernThemeToggle1.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle1.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle1.EnableHover = true;
            modernThemeToggle1.EnablePressEffect = true;
            modernThemeToggle1.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle1.FocusThickness = 0F;
            modernThemeToggle1.FontFamily = "Segoe UI";
            modernThemeToggle1.FontSize = 12F;
            modernThemeToggle1.FontWeightBold = false;
            modernThemeToggle1.HoverColor = Color.Transparent;
            modernThemeToggle1.HoverColor2 = Color.Transparent;
            modernThemeToggle1.ImageOpacity = 1F;
            modernThemeToggle1.Location = new Point(349, 142);
            modernThemeToggle1.MinimumSize = new Size(45, 22);
            modernThemeToggle1.Name = "modernThemeToggle1";
            modernThemeToggle1.Opacity = 1F;
            modernThemeToggle1.PressColor = Color.Transparent;
            modernThemeToggle1.PressColor2 = Color.Transparent;
            modernThemeToggle1.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle1.Rotation = 0F;
            modernThemeToggle1.ScaleX = 1F;
            modernThemeToggle1.ScaleY = 1F;
            modernThemeToggle1.ShadowBlur = 8F;
            modernThemeToggle1.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle1.ShadowOffsetX = 0F;
            modernThemeToggle1.ShadowOffsetY = 4F;
            modernThemeToggle1.ShadowOpacity = 0.5F;
            modernThemeToggle1.Size = new Size(56, 28);
            modernThemeToggle1.Style = Custom_Buttons.ToggleStyle.Weather_Legacy;
            modernThemeToggle1.TabIndex = 0;
            modernThemeToggle1.Text = "modernThemeToggle1";
            modernThemeToggle1.TextAlignment = StringAlignment.Center;
            modernThemeToggle1.TextColor = Color.Black;
            modernThemeToggle1.ThumbColorOff = Color.White;
            modernThemeToggle1.ThumbColorOn = Color.White;
            modernThemeToggle1.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle1.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle1.UseAcrylic = false;
            modernThemeToggle1.UseGradient = false;
            modernThemeToggle1.UseRipple = false;
            modernThemeToggle1.UseShadow = false;
            modernThemeToggle1.UseSkiaGraphics = false;
            modernThemeToggle1.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle1.WordWrap = false;
            // 
            // modernThemeToggle2
            // 
            modernThemeToggle2.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle2.AnimationSpeed = 150F;
            modernThemeToggle2.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle2.BackColor = Color.Transparent;
            modernThemeToggle2.BackgroundColor = Color.Transparent;
            modernThemeToggle2.BackgroundColor2 = Color.Transparent;
            modernThemeToggle2.BackgroundImg = null;
            modernThemeToggle2.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle2.BorderColor = Color.Transparent;
            modernThemeToggle2.BorderRadius = 14F;
            modernThemeToggle2.BorderThickness = 0F;
            modernThemeToggle2.CheckedColor = Color.Transparent;
            modernThemeToggle2.CheckedColor2 = Color.Transparent;
            modernThemeToggle2.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle2.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle2.EnableHover = true;
            modernThemeToggle2.EnablePressEffect = true;
            modernThemeToggle2.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle2.FocusThickness = 0F;
            modernThemeToggle2.FontFamily = "Segoe UI";
            modernThemeToggle2.FontSize = 12F;
            modernThemeToggle2.FontWeightBold = false;
            modernThemeToggle2.HoverColor = Color.Transparent;
            modernThemeToggle2.HoverColor2 = Color.Transparent;
            modernThemeToggle2.ImageOpacity = 1F;
            modernThemeToggle2.Location = new Point(227, 190);
            modernThemeToggle2.MinimumSize = new Size(45, 22);
            modernThemeToggle2.Name = "modernThemeToggle2";
            modernThemeToggle2.Opacity = 1F;
            modernThemeToggle2.PressColor = Color.Transparent;
            modernThemeToggle2.PressColor2 = Color.Transparent;
            modernThemeToggle2.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle2.Rotation = 0F;
            modernThemeToggle2.ScaleX = 1F;
            modernThemeToggle2.ScaleY = 1F;
            modernThemeToggle2.ShadowBlur = 8F;
            modernThemeToggle2.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle2.ShadowOffsetX = 0F;
            modernThemeToggle2.ShadowOffsetY = 4F;
            modernThemeToggle2.ShadowOpacity = 0.5F;
            modernThemeToggle2.Size = new Size(56, 28);
            modernThemeToggle2.Style = Custom_Buttons.ToggleStyle.Style6_WideThumb;
            modernThemeToggle2.TabIndex = 1;
            modernThemeToggle2.Text = "modernThemeToggle2";
            modernThemeToggle2.TextAlignment = StringAlignment.Center;
            modernThemeToggle2.TextColor = Color.Black;
            modernThemeToggle2.ThumbColorOff = Color.White;
            modernThemeToggle2.ThumbColorOn = Color.White;
            modernThemeToggle2.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle2.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle2.UseAcrylic = false;
            modernThemeToggle2.UseGradient = false;
            modernThemeToggle2.UseRipple = false;
            modernThemeToggle2.UseShadow = false;
            modernThemeToggle2.UseSkiaGraphics = true;
            modernThemeToggle2.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle2.WordWrap = false;
            // 
            // modernThemeToggle3
            // 
            modernThemeToggle3.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle3.AnimationSpeed = 150F;
            modernThemeToggle3.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle3.BackColor = Color.Transparent;
            modernThemeToggle3.BackgroundColor = Color.Transparent;
            modernThemeToggle3.BackgroundColor2 = Color.Transparent;
            modernThemeToggle3.BackgroundImg = null;
            modernThemeToggle3.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle3.BorderColor = Color.Transparent;
            modernThemeToggle3.BorderRadius = 14F;
            modernThemeToggle3.BorderThickness = 0F;
            modernThemeToggle3.CheckedColor = Color.Transparent;
            modernThemeToggle3.CheckedColor2 = Color.Transparent;
            modernThemeToggle3.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle3.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle3.EnableHover = true;
            modernThemeToggle3.EnablePressEffect = true;
            modernThemeToggle3.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle3.FocusThickness = 0F;
            modernThemeToggle3.FontFamily = "Segoe UI";
            modernThemeToggle3.FontSize = 12F;
            modernThemeToggle3.FontWeightBold = false;
            modernThemeToggle3.HoverColor = Color.Transparent;
            modernThemeToggle3.HoverColor2 = Color.Transparent;
            modernThemeToggle3.ImageOpacity = 1F;
            modernThemeToggle3.Location = new Point(227, 142);
            modernThemeToggle3.MinimumSize = new Size(45, 22);
            modernThemeToggle3.Name = "modernThemeToggle3";
            modernThemeToggle3.Opacity = 1F;
            modernThemeToggle3.PressColor = Color.Transparent;
            modernThemeToggle3.PressColor2 = Color.Transparent;
            modernThemeToggle3.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle3.Rotation = 0F;
            modernThemeToggle3.ScaleX = 1F;
            modernThemeToggle3.ScaleY = 1F;
            modernThemeToggle3.ShadowBlur = 8F;
            modernThemeToggle3.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle3.ShadowOffsetX = 0F;
            modernThemeToggle3.ShadowOffsetY = 4F;
            modernThemeToggle3.ShadowOpacity = 0.5F;
            modernThemeToggle3.Size = new Size(56, 28);
            modernThemeToggle3.Style = Custom_Buttons.ToggleStyle.Style6_WideThumb;
            modernThemeToggle3.TabIndex = 2;
            modernThemeToggle3.Text = "modernThemeToggle3";
            modernThemeToggle3.TextAlignment = StringAlignment.Center;
            modernThemeToggle3.TextColor = Color.Black;
            modernThemeToggle3.ThumbColorOff = Color.White;
            modernThemeToggle3.ThumbColorOn = Color.White;
            modernThemeToggle3.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle3.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle3.UseAcrylic = false;
            modernThemeToggle3.UseGradient = false;
            modernThemeToggle3.UseRipple = false;
            modernThemeToggle3.UseShadow = false;
            modernThemeToggle3.UseSkiaGraphics = false;
            modernThemeToggle3.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle3.WordWrap = false;
            modernThemeToggle3.Click += modernThemeToggle3_Click;
            // 
            // modernThemeToggle4
            // 
            modernThemeToggle4.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle4.AnimationSpeed = 150F;
            modernThemeToggle4.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle4.BackColor = Color.Transparent;
            modernThemeToggle4.BackgroundColor = Color.Transparent;
            modernThemeToggle4.BackgroundColor2 = Color.Transparent;
            modernThemeToggle4.BackgroundImg = null;
            modernThemeToggle4.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle4.BorderColor = Color.Transparent;
            modernThemeToggle4.BorderRadius = 14F;
            modernThemeToggle4.BorderThickness = 0F;
            modernThemeToggle4.CheckedColor = Color.Transparent;
            modernThemeToggle4.CheckedColor2 = Color.Transparent;
            modernThemeToggle4.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle4.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle4.EnableHover = true;
            modernThemeToggle4.EnablePressEffect = true;
            modernThemeToggle4.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle4.FocusThickness = 0F;
            modernThemeToggle4.FontFamily = "Segoe UI";
            modernThemeToggle4.FontSize = 12F;
            modernThemeToggle4.FontWeightBold = false;
            modernThemeToggle4.HoverColor = Color.Transparent;
            modernThemeToggle4.HoverColor2 = Color.Transparent;
            modernThemeToggle4.ImageOpacity = 1F;
            modernThemeToggle4.Location = new Point(467, 142);
            modernThemeToggle4.MinimumSize = new Size(45, 22);
            modernThemeToggle4.Name = "modernThemeToggle4";
            modernThemeToggle4.Opacity = 1F;
            modernThemeToggle4.PressColor = Color.Transparent;
            modernThemeToggle4.PressColor2 = Color.Transparent;
            modernThemeToggle4.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle4.Rotation = 0F;
            modernThemeToggle4.ScaleX = 1F;
            modernThemeToggle4.ScaleY = 1F;
            modernThemeToggle4.ShadowBlur = 8F;
            modernThemeToggle4.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle4.ShadowOffsetX = 0F;
            modernThemeToggle4.ShadowOffsetY = 4F;
            modernThemeToggle4.ShadowOpacity = 0.5F;
            modernThemeToggle4.Size = new Size(56, 28);
            modernThemeToggle4.Style = Custom_Buttons.ToggleStyle.Style7_Checkmark;
            modernThemeToggle4.TabIndex = 4;
            modernThemeToggle4.Text = "modernThemeToggle4";
            modernThemeToggle4.TextAlignment = StringAlignment.Center;
            modernThemeToggle4.TextColor = Color.Black;
            modernThemeToggle4.ThumbColorOff = Color.White;
            modernThemeToggle4.ThumbColorOn = Color.White;
            modernThemeToggle4.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle4.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle4.UseAcrylic = false;
            modernThemeToggle4.UseGradient = false;
            modernThemeToggle4.UseRipple = false;
            modernThemeToggle4.UseShadow = false;
            modernThemeToggle4.UseSkiaGraphics = false;
            modernThemeToggle4.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle4.WordWrap = false;
            // 
            // modernThemeToggle5
            // 
            modernThemeToggle5.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle5.AnimationSpeed = 150F;
            modernThemeToggle5.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle5.BackColor = Color.Transparent;
            modernThemeToggle5.BackgroundColor = Color.Transparent;
            modernThemeToggle5.BackgroundColor2 = Color.Transparent;
            modernThemeToggle5.BackgroundImg = null;
            modernThemeToggle5.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle5.BorderColor = Color.Transparent;
            modernThemeToggle5.BorderRadius = 14F;
            modernThemeToggle5.BorderThickness = 0F;
            modernThemeToggle5.CheckedColor = Color.Transparent;
            modernThemeToggle5.CheckedColor2 = Color.Transparent;
            modernThemeToggle5.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle5.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle5.EnableHover = true;
            modernThemeToggle5.EnablePressEffect = true;
            modernThemeToggle5.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle5.FocusThickness = 0F;
            modernThemeToggle5.FontFamily = "Segoe UI";
            modernThemeToggle5.FontSize = 12F;
            modernThemeToggle5.FontWeightBold = false;
            modernThemeToggle5.HoverColor = Color.Transparent;
            modernThemeToggle5.HoverColor2 = Color.Transparent;
            modernThemeToggle5.ImageOpacity = 1F;
            modernThemeToggle5.Location = new Point(467, 190);
            modernThemeToggle5.MinimumSize = new Size(45, 22);
            modernThemeToggle5.Name = "modernThemeToggle5";
            modernThemeToggle5.Opacity = 1F;
            modernThemeToggle5.PressColor = Color.Transparent;
            modernThemeToggle5.PressColor2 = Color.Transparent;
            modernThemeToggle5.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle5.Rotation = 0F;
            modernThemeToggle5.ScaleX = 1F;
            modernThemeToggle5.ScaleY = 1F;
            modernThemeToggle5.ShadowBlur = 8F;
            modernThemeToggle5.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle5.ShadowOffsetX = 0F;
            modernThemeToggle5.ShadowOffsetY = 4F;
            modernThemeToggle5.ShadowOpacity = 0.5F;
            modernThemeToggle5.Size = new Size(56, 28);
            modernThemeToggle5.Style = Custom_Buttons.ToggleStyle.Style7_Checkmark;
            modernThemeToggle5.TabIndex = 3;
            modernThemeToggle5.Text = "modernThemeToggle5";
            modernThemeToggle5.TextAlignment = StringAlignment.Center;
            modernThemeToggle5.TextColor = Color.Black;
            modernThemeToggle5.ThumbColorOff = Color.White;
            modernThemeToggle5.ThumbColorOn = Color.White;
            modernThemeToggle5.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle5.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle5.UseAcrylic = false;
            modernThemeToggle5.UseGradient = false;
            modernThemeToggle5.UseRipple = false;
            modernThemeToggle5.UseShadow = false;
            modernThemeToggle5.UseSkiaGraphics = true;
            modernThemeToggle5.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle5.WordWrap = false;
            // 
            // modernThemeToggle6
            // 
            modernThemeToggle6.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle6.AnimationSpeed = 150F;
            modernThemeToggle6.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle6.BackColor = Color.Transparent;
            modernThemeToggle6.BackgroundColor = Color.Transparent;
            modernThemeToggle6.BackgroundColor2 = Color.Transparent;
            modernThemeToggle6.BackgroundImg = null;
            modernThemeToggle6.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle6.BorderColor = Color.Transparent;
            modernThemeToggle6.BorderRadius = 14F;
            modernThemeToggle6.BorderThickness = 0F;
            modernThemeToggle6.CheckedColor = Color.Transparent;
            modernThemeToggle6.CheckedColor2 = Color.Transparent;
            modernThemeToggle6.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle6.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle6.EnableHover = true;
            modernThemeToggle6.EnablePressEffect = true;
            modernThemeToggle6.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle6.FocusThickness = 0F;
            modernThemeToggle6.FontFamily = "Segoe UI";
            modernThemeToggle6.FontSize = 12F;
            modernThemeToggle6.FontWeightBold = false;
            modernThemeToggle6.HoverColor = Color.Transparent;
            modernThemeToggle6.HoverColor2 = Color.Transparent;
            modernThemeToggle6.ImageOpacity = 1F;
            modernThemeToggle6.Location = new Point(111, 145);
            modernThemeToggle6.MinimumSize = new Size(45, 22);
            modernThemeToggle6.Name = "modernThemeToggle6";
            modernThemeToggle6.Opacity = 1F;
            modernThemeToggle6.PressColor = Color.Transparent;
            modernThemeToggle6.PressColor2 = Color.Transparent;
            modernThemeToggle6.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle6.Rotation = 0F;
            modernThemeToggle6.ScaleX = 1F;
            modernThemeToggle6.ScaleY = 1F;
            modernThemeToggle6.ShadowBlur = 8F;
            modernThemeToggle6.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle6.ShadowOffsetX = 0F;
            modernThemeToggle6.ShadowOffsetY = 4F;
            modernThemeToggle6.ShadowOpacity = 0.5F;
            modernThemeToggle6.Size = new Size(56, 28);
            modernThemeToggle6.Style = Custom_Buttons.ToggleStyle.Style9_MinimalDayNight;
            modernThemeToggle6.TabIndex = 6;
            modernThemeToggle6.Text = "modernThemeToggle6";
            modernThemeToggle6.TextAlignment = StringAlignment.Center;
            modernThemeToggle6.TextColor = Color.Black;
            modernThemeToggle6.ThumbColorOff = Color.White;
            modernThemeToggle6.ThumbColorOn = Color.White;
            modernThemeToggle6.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle6.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle6.UseAcrylic = false;
            modernThemeToggle6.UseGradient = false;
            modernThemeToggle6.UseRipple = false;
            modernThemeToggle6.UseShadow = false;
            modernThemeToggle6.UseSkiaGraphics = false;
            modernThemeToggle6.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle6.WordWrap = false;
            // 
            // modernThemeToggle7
            // 
            modernThemeToggle7.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle7.AnimationSpeed = 150F;
            modernThemeToggle7.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle7.BackColor = Color.Transparent;
            modernThemeToggle7.BackgroundColor = Color.Transparent;
            modernThemeToggle7.BackgroundColor2 = Color.Transparent;
            modernThemeToggle7.BackgroundImg = null;
            modernThemeToggle7.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle7.BorderColor = Color.Transparent;
            modernThemeToggle7.BorderRadius = 14F;
            modernThemeToggle7.BorderThickness = 0F;
            modernThemeToggle7.CheckedColor = Color.Transparent;
            modernThemeToggle7.CheckedColor2 = Color.Transparent;
            modernThemeToggle7.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle7.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle7.EnableHover = true;
            modernThemeToggle7.EnablePressEffect = true;
            modernThemeToggle7.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle7.FocusThickness = 0F;
            modernThemeToggle7.FontFamily = "Segoe UI";
            modernThemeToggle7.FontSize = 12F;
            modernThemeToggle7.FontWeightBold = false;
            modernThemeToggle7.HoverColor = Color.Transparent;
            modernThemeToggle7.HoverColor2 = Color.Transparent;
            modernThemeToggle7.ImageOpacity = 1F;
            modernThemeToggle7.Location = new Point(111, 190);
            modernThemeToggle7.MinimumSize = new Size(45, 22);
            modernThemeToggle7.Name = "modernThemeToggle7";
            modernThemeToggle7.Opacity = 1F;
            modernThemeToggle7.PressColor = Color.Transparent;
            modernThemeToggle7.PressColor2 = Color.Transparent;
            modernThemeToggle7.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle7.Rotation = 0F;
            modernThemeToggle7.ScaleX = 1F;
            modernThemeToggle7.ScaleY = 1F;
            modernThemeToggle7.ShadowBlur = 8F;
            modernThemeToggle7.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle7.ShadowOffsetX = 0F;
            modernThemeToggle7.ShadowOffsetY = 4F;
            modernThemeToggle7.ShadowOpacity = 0.5F;
            modernThemeToggle7.Size = new Size(56, 28);
            modernThemeToggle7.Style = Custom_Buttons.ToggleStyle.Style9_MinimalDayNight;
            modernThemeToggle7.TabIndex = 5;
            modernThemeToggle7.Text = "modernThemeToggle7";
            modernThemeToggle7.TextAlignment = StringAlignment.Center;
            modernThemeToggle7.TextColor = Color.Black;
            modernThemeToggle7.ThumbColorOff = Color.White;
            modernThemeToggle7.ThumbColorOn = Color.White;
            modernThemeToggle7.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle7.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle7.UseAcrylic = false;
            modernThemeToggle7.UseGradient = false;
            modernThemeToggle7.UseRipple = false;
            modernThemeToggle7.UseShadow = false;
            modernThemeToggle7.UseSkiaGraphics = true;
            modernThemeToggle7.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle7.WordWrap = false;
            // 
            // modernThemeToggle8
            // 
            modernThemeToggle8.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle8.AnimationSpeed = 150F;
            modernThemeToggle8.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle8.BackColor = Color.Transparent;
            modernThemeToggle8.BackgroundColor = Color.Transparent;
            modernThemeToggle8.BackgroundColor2 = Color.Transparent;
            modernThemeToggle8.BackgroundImg = null;
            modernThemeToggle8.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle8.BorderColor = Color.Transparent;
            modernThemeToggle8.BorderRadius = 14F;
            modernThemeToggle8.BorderThickness = 0F;
            modernThemeToggle8.CheckedColor = Color.Transparent;
            modernThemeToggle8.CheckedColor2 = Color.Transparent;
            modernThemeToggle8.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle8.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle8.EnableHover = true;
            modernThemeToggle8.EnablePressEffect = true;
            modernThemeToggle8.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle8.FocusThickness = 0F;
            modernThemeToggle8.FontFamily = "Segoe UI";
            modernThemeToggle8.FontSize = 12F;
            modernThemeToggle8.FontWeightBold = false;
            modernThemeToggle8.HoverColor = Color.Transparent;
            modernThemeToggle8.HoverColor2 = Color.Transparent;
            modernThemeToggle8.ImageOpacity = 1F;
            modernThemeToggle8.Location = new Point(574, 145);
            modernThemeToggle8.MinimumSize = new Size(45, 22);
            modernThemeToggle8.Name = "modernThemeToggle8";
            modernThemeToggle8.Opacity = 1F;
            modernThemeToggle8.PressColor = Color.Transparent;
            modernThemeToggle8.PressColor2 = Color.Transparent;
            modernThemeToggle8.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle8.Rotation = 0F;
            modernThemeToggle8.ScaleX = 1F;
            modernThemeToggle8.ScaleY = 1F;
            modernThemeToggle8.ShadowBlur = 8F;
            modernThemeToggle8.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle8.ShadowOffsetX = 0F;
            modernThemeToggle8.ShadowOffsetY = 4F;
            modernThemeToggle8.ShadowOpacity = 0.5F;
            modernThemeToggle8.Size = new Size(56, 28);
            modernThemeToggle8.Style = Custom_Buttons.ToggleStyle.Style8_Ring;
            modernThemeToggle8.TabIndex = 8;
            modernThemeToggle8.Text = "modernThemeToggle8";
            modernThemeToggle8.TextAlignment = StringAlignment.Center;
            modernThemeToggle8.TextColor = Color.Black;
            modernThemeToggle8.ThumbColorOff = Color.White;
            modernThemeToggle8.ThumbColorOn = Color.White;
            modernThemeToggle8.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle8.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle8.UseAcrylic = false;
            modernThemeToggle8.UseGradient = false;
            modernThemeToggle8.UseRipple = false;
            modernThemeToggle8.UseShadow = false;
            modernThemeToggle8.UseSkiaGraphics = false;
            modernThemeToggle8.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle8.WordWrap = false;
            // 
            // modernThemeToggle9
            // 
            modernThemeToggle9.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle9.AnimationSpeed = 150F;
            modernThemeToggle9.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle9.BackColor = Color.Transparent;
            modernThemeToggle9.BackgroundColor = Color.Transparent;
            modernThemeToggle9.BackgroundColor2 = Color.Transparent;
            modernThemeToggle9.BackgroundImg = null;
            modernThemeToggle9.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle9.BorderColor = Color.Transparent;
            modernThemeToggle9.BorderRadius = 14F;
            modernThemeToggle9.BorderThickness = 0F;
            modernThemeToggle9.CheckedColor = Color.Transparent;
            modernThemeToggle9.CheckedColor2 = Color.Transparent;
            modernThemeToggle9.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle9.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle9.EnableHover = true;
            modernThemeToggle9.EnablePressEffect = true;
            modernThemeToggle9.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle9.FocusThickness = 0F;
            modernThemeToggle9.FontFamily = "Segoe UI";
            modernThemeToggle9.FontSize = 12F;
            modernThemeToggle9.FontWeightBold = false;
            modernThemeToggle9.HoverColor = Color.Transparent;
            modernThemeToggle9.HoverColor2 = Color.Transparent;
            modernThemeToggle9.ImageOpacity = 1F;
            modernThemeToggle9.Location = new Point(574, 190);
            modernThemeToggle9.MinimumSize = new Size(45, 22);
            modernThemeToggle9.Name = "modernThemeToggle9";
            modernThemeToggle9.Opacity = 1F;
            modernThemeToggle9.PressColor = Color.Transparent;
            modernThemeToggle9.PressColor2 = Color.Transparent;
            modernThemeToggle9.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle9.Rotation = 0F;
            modernThemeToggle9.ScaleX = 1F;
            modernThemeToggle9.ScaleY = 1F;
            modernThemeToggle9.ShadowBlur = 8F;
            modernThemeToggle9.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle9.ShadowOffsetX = 0F;
            modernThemeToggle9.ShadowOffsetY = 4F;
            modernThemeToggle9.ShadowOpacity = 0.5F;
            modernThemeToggle9.Size = new Size(56, 28);
            modernThemeToggle9.Style = Custom_Buttons.ToggleStyle.Style8_Ring;
            modernThemeToggle9.TabIndex = 7;
            modernThemeToggle9.Text = "modernThemeToggle9";
            modernThemeToggle9.TextAlignment = StringAlignment.Center;
            modernThemeToggle9.TextColor = Color.Black;
            modernThemeToggle9.ThumbColorOff = Color.White;
            modernThemeToggle9.ThumbColorOn = Color.White;
            modernThemeToggle9.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle9.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle9.UseAcrylic = false;
            modernThemeToggle9.UseGradient = false;
            modernThemeToggle9.UseRipple = false;
            modernThemeToggle9.UseShadow = false;
            modernThemeToggle9.UseSkiaGraphics = true;
            modernThemeToggle9.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle9.WordWrap = false;
            // 
            // modernThemeToggle10
            // 
            modernThemeToggle10.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle10.AnimationSpeed = 150F;
            modernThemeToggle10.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle10.BackColor = Color.Transparent;
            modernThemeToggle10.BackgroundColor = Color.Transparent;
            modernThemeToggle10.BackgroundColor2 = Color.Transparent;
            modernThemeToggle10.BackgroundImg = null;
            modernThemeToggle10.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle10.BorderColor = Color.Transparent;
            modernThemeToggle10.BorderRadius = 14F;
            modernThemeToggle10.BorderThickness = 0F;
            modernThemeToggle10.CheckedColor = Color.Transparent;
            modernThemeToggle10.CheckedColor2 = Color.Transparent;
            modernThemeToggle10.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle10.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle10.EnableHover = true;
            modernThemeToggle10.EnablePressEffect = true;
            modernThemeToggle10.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle10.FocusThickness = 0F;
            modernThemeToggle10.FontFamily = "Segoe UI";
            modernThemeToggle10.FontSize = 12F;
            modernThemeToggle10.FontWeightBold = false;
            modernThemeToggle10.HoverColor = Color.Transparent;
            modernThemeToggle10.HoverColor2 = Color.Transparent;
            modernThemeToggle10.ImageOpacity = 1F;
            modernThemeToggle10.Location = new Point(349, 190);
            modernThemeToggle10.MinimumSize = new Size(45, 22);
            modernThemeToggle10.Name = "modernThemeToggle10";
            modernThemeToggle10.Opacity = 1F;
            modernThemeToggle10.PressColor = Color.Transparent;
            modernThemeToggle10.PressColor2 = Color.Transparent;
            modernThemeToggle10.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle10.Rotation = 0F;
            modernThemeToggle10.ScaleX = 1F;
            modernThemeToggle10.ScaleY = 1F;
            modernThemeToggle10.ShadowBlur = 8F;
            modernThemeToggle10.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle10.ShadowOffsetX = 0F;
            modernThemeToggle10.ShadowOffsetY = 4F;
            modernThemeToggle10.ShadowOpacity = 0.5F;
            modernThemeToggle10.Size = new Size(56, 28);
            modernThemeToggle10.Style = Custom_Buttons.ToggleStyle.Weather_Legacy;
            modernThemeToggle10.TabIndex = 9;
            modernThemeToggle10.Text = "modernThemeToggle10";
            modernThemeToggle10.TextAlignment = StringAlignment.Center;
            modernThemeToggle10.TextColor = Color.Black;
            modernThemeToggle10.ThumbColorOff = Color.White;
            modernThemeToggle10.ThumbColorOn = Color.White;
            modernThemeToggle10.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle10.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle10.UseAcrylic = false;
            modernThemeToggle10.UseGradient = false;
            modernThemeToggle10.UseRipple = false;
            modernThemeToggle10.UseShadow = false;
            modernThemeToggle10.UseSkiaGraphics = true;
            modernThemeToggle10.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle10.WordWrap = false;
            // 
            // modernThemeToggle11
            // 
            modernThemeToggle11.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle11.AnimationSpeed = 150F;
            modernThemeToggle11.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle11.BackColor = Color.Transparent;
            modernThemeToggle11.BackgroundColor = Color.Transparent;
            modernThemeToggle11.BackgroundColor2 = Color.Transparent;
            modernThemeToggle11.BackgroundImg = null;
            modernThemeToggle11.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle11.BorderColor = Color.Transparent;
            modernThemeToggle11.BorderRadius = 14F;
            modernThemeToggle11.BorderThickness = 0F;
            modernThemeToggle11.CheckedColor = Color.Transparent;
            modernThemeToggle11.CheckedColor2 = Color.Transparent;
            modernThemeToggle11.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle11.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle11.EnableHover = true;
            modernThemeToggle11.EnablePressEffect = true;
            modernThemeToggle11.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle11.FocusThickness = 0F;
            modernThemeToggle11.FontFamily = "Segoe UI";
            modernThemeToggle11.FontSize = 12F;
            modernThemeToggle11.FontWeightBold = false;
            modernThemeToggle11.HoverColor = Color.Transparent;
            modernThemeToggle11.HoverColor2 = Color.Transparent;
            modernThemeToggle11.ImageOpacity = 1F;
            modernThemeToggle11.Location = new Point(349, 313);
            modernThemeToggle11.MinimumSize = new Size(45, 22);
            modernThemeToggle11.Name = "modernThemeToggle11";
            modernThemeToggle11.Opacity = 1F;
            modernThemeToggle11.PressColor = Color.Transparent;
            modernThemeToggle11.PressColor2 = Color.Transparent;
            modernThemeToggle11.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle11.Rotation = 0F;
            modernThemeToggle11.ScaleX = 1F;
            modernThemeToggle11.ScaleY = 1F;
            modernThemeToggle11.ShadowBlur = 8F;
            modernThemeToggle11.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle11.ShadowOffsetX = 0F;
            modernThemeToggle11.ShadowOffsetY = 4F;
            modernThemeToggle11.ShadowOpacity = 0.5F;
            modernThemeToggle11.Size = new Size(56, 28);
            modernThemeToggle11.Style = Custom_Buttons.ToggleStyle.Style3_LineTrack;
            modernThemeToggle11.TabIndex = 19;
            modernThemeToggle11.Text = "modernThemeToggle11";
            modernThemeToggle11.TextAlignment = StringAlignment.Center;
            modernThemeToggle11.TextColor = Color.Black;
            modernThemeToggle11.ThumbColorOff = Color.White;
            modernThemeToggle11.ThumbColorOn = Color.White;
            modernThemeToggle11.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle11.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle11.UseAcrylic = false;
            modernThemeToggle11.UseGradient = false;
            modernThemeToggle11.UseRipple = false;
            modernThemeToggle11.UseShadow = false;
            modernThemeToggle11.UseSkiaGraphics = true;
            modernThemeToggle11.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle11.WordWrap = false;
            // 
            // modernThemeToggle12
            // 
            modernThemeToggle12.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle12.AnimationSpeed = 150F;
            modernThemeToggle12.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle12.BackColor = Color.Transparent;
            modernThemeToggle12.BackgroundColor = Color.Transparent;
            modernThemeToggle12.BackgroundColor2 = Color.Transparent;
            modernThemeToggle12.BackgroundImg = null;
            modernThemeToggle12.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle12.BorderColor = Color.Transparent;
            modernThemeToggle12.BorderRadius = 14F;
            modernThemeToggle12.BorderThickness = 0F;
            modernThemeToggle12.CheckedColor = Color.Transparent;
            modernThemeToggle12.CheckedColor2 = Color.Transparent;
            modernThemeToggle12.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle12.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle12.EnableHover = true;
            modernThemeToggle12.EnablePressEffect = true;
            modernThemeToggle12.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle12.FocusThickness = 0F;
            modernThemeToggle12.FontFamily = "Segoe UI";
            modernThemeToggle12.FontSize = 12F;
            modernThemeToggle12.FontWeightBold = false;
            modernThemeToggle12.HoverColor = Color.Transparent;
            modernThemeToggle12.HoverColor2 = Color.Transparent;
            modernThemeToggle12.ImageOpacity = 1F;
            modernThemeToggle12.Location = new Point(574, 268);
            modernThemeToggle12.MinimumSize = new Size(45, 22);
            modernThemeToggle12.Name = "modernThemeToggle12";
            modernThemeToggle12.Opacity = 1F;
            modernThemeToggle12.PressColor = Color.Transparent;
            modernThemeToggle12.PressColor2 = Color.Transparent;
            modernThemeToggle12.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle12.Rotation = 0F;
            modernThemeToggle12.ScaleX = 1F;
            modernThemeToggle12.ScaleY = 1F;
            modernThemeToggle12.ShadowBlur = 8F;
            modernThemeToggle12.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle12.ShadowOffsetX = 0F;
            modernThemeToggle12.ShadowOffsetY = 4F;
            modernThemeToggle12.ShadowOpacity = 0.5F;
            modernThemeToggle12.Size = new Size(56, 28);
            modernThemeToggle12.Style = Custom_Buttons.ToggleStyle.Style5_Text;
            modernThemeToggle12.TabIndex = 18;
            modernThemeToggle12.Text = "modernThemeToggle12";
            modernThemeToggle12.TextAlignment = StringAlignment.Center;
            modernThemeToggle12.TextColor = Color.Black;
            modernThemeToggle12.ThumbColorOff = Color.White;
            modernThemeToggle12.ThumbColorOn = Color.White;
            modernThemeToggle12.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle12.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle12.UseAcrylic = false;
            modernThemeToggle12.UseGradient = false;
            modernThemeToggle12.UseRipple = false;
            modernThemeToggle12.UseShadow = false;
            modernThemeToggle12.UseSkiaGraphics = false;
            modernThemeToggle12.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle12.WordWrap = false;
            // 
            // modernThemeToggle13
            // 
            modernThemeToggle13.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle13.AnimationSpeed = 150F;
            modernThemeToggle13.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle13.BackColor = Color.Transparent;
            modernThemeToggle13.BackgroundColor = Color.Transparent;
            modernThemeToggle13.BackgroundColor2 = Color.Transparent;
            modernThemeToggle13.BackgroundImg = null;
            modernThemeToggle13.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle13.BorderColor = Color.Transparent;
            modernThemeToggle13.BorderRadius = 14F;
            modernThemeToggle13.BorderThickness = 0F;
            modernThemeToggle13.CheckedColor = Color.Transparent;
            modernThemeToggle13.CheckedColor2 = Color.Transparent;
            modernThemeToggle13.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle13.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle13.EnableHover = true;
            modernThemeToggle13.EnablePressEffect = true;
            modernThemeToggle13.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle13.FocusThickness = 0F;
            modernThemeToggle13.FontFamily = "Segoe UI";
            modernThemeToggle13.FontSize = 12F;
            modernThemeToggle13.FontWeightBold = false;
            modernThemeToggle13.HoverColor = Color.Transparent;
            modernThemeToggle13.HoverColor2 = Color.Transparent;
            modernThemeToggle13.ImageOpacity = 1F;
            modernThemeToggle13.Location = new Point(574, 313);
            modernThemeToggle13.MinimumSize = new Size(45, 22);
            modernThemeToggle13.Name = "modernThemeToggle13";
            modernThemeToggle13.Opacity = 1F;
            modernThemeToggle13.PressColor = Color.Transparent;
            modernThemeToggle13.PressColor2 = Color.Transparent;
            modernThemeToggle13.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle13.Rotation = 0F;
            modernThemeToggle13.ScaleX = 1F;
            modernThemeToggle13.ScaleY = 1F;
            modernThemeToggle13.ShadowBlur = 8F;
            modernThemeToggle13.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle13.ShadowOffsetX = 0F;
            modernThemeToggle13.ShadowOffsetY = 4F;
            modernThemeToggle13.ShadowOpacity = 0.5F;
            modernThemeToggle13.Size = new Size(56, 28);
            modernThemeToggle13.Style = Custom_Buttons.ToggleStyle.Style5_Text;
            modernThemeToggle13.TabIndex = 17;
            modernThemeToggle13.Text = "modernThemeToggle13";
            modernThemeToggle13.TextAlignment = StringAlignment.Center;
            modernThemeToggle13.TextColor = Color.Black;
            modernThemeToggle13.ThumbColorOff = Color.White;
            modernThemeToggle13.ThumbColorOn = Color.White;
            modernThemeToggle13.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle13.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle13.UseAcrylic = false;
            modernThemeToggle13.UseGradient = false;
            modernThemeToggle13.UseRipple = false;
            modernThemeToggle13.UseShadow = false;
            modernThemeToggle13.UseSkiaGraphics = true;
            modernThemeToggle13.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle13.WordWrap = false;
            // 
            // modernThemeToggle14
            // 
            modernThemeToggle14.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle14.AnimationSpeed = 150F;
            modernThemeToggle14.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle14.BackColor = Color.Transparent;
            modernThemeToggle14.BackgroundColor = Color.Transparent;
            modernThemeToggle14.BackgroundColor2 = Color.Transparent;
            modernThemeToggle14.BackgroundImg = null;
            modernThemeToggle14.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle14.BorderColor = Color.Transparent;
            modernThemeToggle14.BorderRadius = 14F;
            modernThemeToggle14.BorderThickness = 0F;
            modernThemeToggle14.CheckedColor = Color.Transparent;
            modernThemeToggle14.CheckedColor2 = Color.Transparent;
            modernThemeToggle14.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle14.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle14.EnableHover = true;
            modernThemeToggle14.EnablePressEffect = true;
            modernThemeToggle14.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle14.FocusThickness = 0F;
            modernThemeToggle14.FontFamily = "Segoe UI";
            modernThemeToggle14.FontSize = 12F;
            modernThemeToggle14.FontWeightBold = false;
            modernThemeToggle14.HoverColor = Color.Transparent;
            modernThemeToggle14.HoverColor2 = Color.Transparent;
            modernThemeToggle14.ImageOpacity = 1F;
            modernThemeToggle14.Location = new Point(111, 268);
            modernThemeToggle14.MinimumSize = new Size(45, 22);
            modernThemeToggle14.Name = "modernThemeToggle14";
            modernThemeToggle14.Opacity = 1F;
            modernThemeToggle14.PressColor = Color.Transparent;
            modernThemeToggle14.PressColor2 = Color.Transparent;
            modernThemeToggle14.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle14.Rotation = 0F;
            modernThemeToggle14.ScaleX = 1F;
            modernThemeToggle14.ScaleY = 1F;
            modernThemeToggle14.ShadowBlur = 8F;
            modernThemeToggle14.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle14.ShadowOffsetX = 0F;
            modernThemeToggle14.ShadowOffsetY = 4F;
            modernThemeToggle14.ShadowOpacity = 0.5F;
            modernThemeToggle14.Size = new Size(56, 28);
            modernThemeToggle14.Style = Custom_Buttons.ToggleStyle.Style1_Standard;
            modernThemeToggle14.TabIndex = 16;
            modernThemeToggle14.Text = "modernThemeToggle14";
            modernThemeToggle14.TextAlignment = StringAlignment.Center;
            modernThemeToggle14.TextColor = Color.Black;
            modernThemeToggle14.ThumbColorOff = Color.White;
            modernThemeToggle14.ThumbColorOn = Color.White;
            modernThemeToggle14.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle14.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle14.UseAcrylic = false;
            modernThemeToggle14.UseGradient = false;
            modernThemeToggle14.UseRipple = false;
            modernThemeToggle14.UseShadow = false;
            modernThemeToggle14.UseSkiaGraphics = false;
            modernThemeToggle14.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle14.WordWrap = false;
            // 
            // modernThemeToggle15
            // 
            modernThemeToggle15.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle15.AnimationSpeed = 150F;
            modernThemeToggle15.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle15.BackColor = Color.Transparent;
            modernThemeToggle15.BackgroundColor = Color.Transparent;
            modernThemeToggle15.BackgroundColor2 = Color.Transparent;
            modernThemeToggle15.BackgroundImg = null;
            modernThemeToggle15.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle15.BorderColor = Color.Transparent;
            modernThemeToggle15.BorderRadius = 14F;
            modernThemeToggle15.BorderThickness = 0F;
            modernThemeToggle15.CheckedColor = Color.Transparent;
            modernThemeToggle15.CheckedColor2 = Color.Transparent;
            modernThemeToggle15.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle15.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle15.EnableHover = true;
            modernThemeToggle15.EnablePressEffect = true;
            modernThemeToggle15.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle15.FocusThickness = 0F;
            modernThemeToggle15.FontFamily = "Segoe UI";
            modernThemeToggle15.FontSize = 12F;
            modernThemeToggle15.FontWeightBold = false;
            modernThemeToggle15.HoverColor = Color.Transparent;
            modernThemeToggle15.HoverColor2 = Color.Transparent;
            modernThemeToggle15.ImageOpacity = 1F;
            modernThemeToggle15.Location = new Point(111, 313);
            modernThemeToggle15.MinimumSize = new Size(45, 22);
            modernThemeToggle15.Name = "modernThemeToggle15";
            modernThemeToggle15.Opacity = 1F;
            modernThemeToggle15.PressColor = Color.Transparent;
            modernThemeToggle15.PressColor2 = Color.Transparent;
            modernThemeToggle15.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle15.Rotation = 0F;
            modernThemeToggle15.ScaleX = 1F;
            modernThemeToggle15.ScaleY = 1F;
            modernThemeToggle15.ShadowBlur = 8F;
            modernThemeToggle15.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle15.ShadowOffsetX = 0F;
            modernThemeToggle15.ShadowOffsetY = 4F;
            modernThemeToggle15.ShadowOpacity = 0.5F;
            modernThemeToggle15.Size = new Size(56, 28);
            modernThemeToggle15.Style = Custom_Buttons.ToggleStyle.Style1_Standard;
            modernThemeToggle15.TabIndex = 15;
            modernThemeToggle15.Text = "modernThemeToggle15";
            modernThemeToggle15.TextAlignment = StringAlignment.Center;
            modernThemeToggle15.TextColor = Color.Black;
            modernThemeToggle15.ThumbColorOff = Color.White;
            modernThemeToggle15.ThumbColorOn = Color.White;
            modernThemeToggle15.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle15.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle15.UseAcrylic = false;
            modernThemeToggle15.UseGradient = false;
            modernThemeToggle15.UseRipple = false;
            modernThemeToggle15.UseShadow = false;
            modernThemeToggle15.UseSkiaGraphics = true;
            modernThemeToggle15.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle15.WordWrap = false;
            // 
            // modernThemeToggle16
            // 
            modernThemeToggle16.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle16.AnimationSpeed = 150F;
            modernThemeToggle16.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle16.BackColor = Color.Transparent;
            modernThemeToggle16.BackgroundColor = Color.Transparent;
            modernThemeToggle16.BackgroundColor2 = Color.Transparent;
            modernThemeToggle16.BackgroundImg = null;
            modernThemeToggle16.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle16.BorderColor = Color.Transparent;
            modernThemeToggle16.BorderRadius = 14F;
            modernThemeToggle16.BorderThickness = 0F;
            modernThemeToggle16.CheckedColor = Color.Transparent;
            modernThemeToggle16.CheckedColor2 = Color.Transparent;
            modernThemeToggle16.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle16.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle16.EnableHover = true;
            modernThemeToggle16.EnablePressEffect = true;
            modernThemeToggle16.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle16.FocusThickness = 0F;
            modernThemeToggle16.FontFamily = "Segoe UI";
            modernThemeToggle16.FontSize = 12F;
            modernThemeToggle16.FontWeightBold = false;
            modernThemeToggle16.HoverColor = Color.Transparent;
            modernThemeToggle16.HoverColor2 = Color.Transparent;
            modernThemeToggle16.ImageOpacity = 1F;
            modernThemeToggle16.Location = new Point(467, 265);
            modernThemeToggle16.MinimumSize = new Size(45, 22);
            modernThemeToggle16.Name = "modernThemeToggle16";
            modernThemeToggle16.Opacity = 1F;
            modernThemeToggle16.PressColor = Color.Transparent;
            modernThemeToggle16.PressColor2 = Color.Transparent;
            modernThemeToggle16.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle16.Rotation = 0F;
            modernThemeToggle16.ScaleX = 1F;
            modernThemeToggle16.ScaleY = 1F;
            modernThemeToggle16.ShadowBlur = 8F;
            modernThemeToggle16.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle16.ShadowOffsetX = 0F;
            modernThemeToggle16.ShadowOffsetY = 4F;
            modernThemeToggle16.ShadowOpacity = 0.5F;
            modernThemeToggle16.Size = new Size(56, 28);
            modernThemeToggle16.Style = Custom_Buttons.ToggleStyle.Style4_Square;
            modernThemeToggle16.TabIndex = 14;
            modernThemeToggle16.Text = "modernThemeToggle16";
            modernThemeToggle16.TextAlignment = StringAlignment.Center;
            modernThemeToggle16.TextColor = Color.Black;
            modernThemeToggle16.ThumbColorOff = Color.White;
            modernThemeToggle16.ThumbColorOn = Color.White;
            modernThemeToggle16.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle16.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle16.UseAcrylic = false;
            modernThemeToggle16.UseGradient = false;
            modernThemeToggle16.UseRipple = false;
            modernThemeToggle16.UseShadow = false;
            modernThemeToggle16.UseSkiaGraphics = false;
            modernThemeToggle16.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle16.WordWrap = false;
            // 
            // modernThemeToggle17
            // 
            modernThemeToggle17.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle17.AnimationSpeed = 150F;
            modernThemeToggle17.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle17.BackColor = Color.Transparent;
            modernThemeToggle17.BackgroundColor = Color.Transparent;
            modernThemeToggle17.BackgroundColor2 = Color.Transparent;
            modernThemeToggle17.BackgroundImg = null;
            modernThemeToggle17.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle17.BorderColor = Color.Transparent;
            modernThemeToggle17.BorderRadius = 14F;
            modernThemeToggle17.BorderThickness = 0F;
            modernThemeToggle17.CheckedColor = Color.Transparent;
            modernThemeToggle17.CheckedColor2 = Color.Transparent;
            modernThemeToggle17.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle17.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle17.EnableHover = true;
            modernThemeToggle17.EnablePressEffect = true;
            modernThemeToggle17.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle17.FocusThickness = 0F;
            modernThemeToggle17.FontFamily = "Segoe UI";
            modernThemeToggle17.FontSize = 12F;
            modernThemeToggle17.FontWeightBold = false;
            modernThemeToggle17.HoverColor = Color.Transparent;
            modernThemeToggle17.HoverColor2 = Color.Transparent;
            modernThemeToggle17.ImageOpacity = 1F;
            modernThemeToggle17.Location = new Point(467, 313);
            modernThemeToggle17.MinimumSize = new Size(45, 22);
            modernThemeToggle17.Name = "modernThemeToggle17";
            modernThemeToggle17.Opacity = 1F;
            modernThemeToggle17.PressColor = Color.Transparent;
            modernThemeToggle17.PressColor2 = Color.Transparent;
            modernThemeToggle17.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle17.Rotation = 0F;
            modernThemeToggle17.ScaleX = 1F;
            modernThemeToggle17.ScaleY = 1F;
            modernThemeToggle17.ShadowBlur = 8F;
            modernThemeToggle17.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle17.ShadowOffsetX = 0F;
            modernThemeToggle17.ShadowOffsetY = 4F;
            modernThemeToggle17.ShadowOpacity = 0.5F;
            modernThemeToggle17.Size = new Size(56, 28);
            modernThemeToggle17.Style = Custom_Buttons.ToggleStyle.Style4_Square;
            modernThemeToggle17.TabIndex = 13;
            modernThemeToggle17.Text = "modernThemeToggle17";
            modernThemeToggle17.TextAlignment = StringAlignment.Center;
            modernThemeToggle17.TextColor = Color.Black;
            modernThemeToggle17.ThumbColorOff = Color.White;
            modernThemeToggle17.ThumbColorOn = Color.White;
            modernThemeToggle17.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle17.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle17.UseAcrylic = false;
            modernThemeToggle17.UseGradient = false;
            modernThemeToggle17.UseRipple = false;
            modernThemeToggle17.UseShadow = false;
            modernThemeToggle17.UseSkiaGraphics = true;
            modernThemeToggle17.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle17.WordWrap = false;
            // 
            // modernThemeToggle18
            // 
            modernThemeToggle18.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle18.AnimationSpeed = 150F;
            modernThemeToggle18.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle18.BackColor = Color.Transparent;
            modernThemeToggle18.BackgroundColor = Color.Transparent;
            modernThemeToggle18.BackgroundColor2 = Color.Transparent;
            modernThemeToggle18.BackgroundImg = null;
            modernThemeToggle18.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle18.BorderColor = Color.Transparent;
            modernThemeToggle18.BorderRadius = 14F;
            modernThemeToggle18.BorderThickness = 0F;
            modernThemeToggle18.CheckedColor = Color.Transparent;
            modernThemeToggle18.CheckedColor2 = Color.Transparent;
            modernThemeToggle18.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle18.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle18.EnableHover = true;
            modernThemeToggle18.EnablePressEffect = true;
            modernThemeToggle18.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle18.FocusThickness = 0F;
            modernThemeToggle18.FontFamily = "Segoe UI";
            modernThemeToggle18.FontSize = 12F;
            modernThemeToggle18.FontWeightBold = false;
            modernThemeToggle18.HoverColor = Color.Transparent;
            modernThemeToggle18.HoverColor2 = Color.Transparent;
            modernThemeToggle18.ImageOpacity = 1F;
            modernThemeToggle18.Location = new Point(227, 265);
            modernThemeToggle18.MinimumSize = new Size(45, 22);
            modernThemeToggle18.Name = "modernThemeToggle18";
            modernThemeToggle18.Opacity = 1F;
            modernThemeToggle18.PressColor = Color.Transparent;
            modernThemeToggle18.PressColor2 = Color.Transparent;
            modernThemeToggle18.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle18.Rotation = 0F;
            modernThemeToggle18.ScaleX = 1F;
            modernThemeToggle18.ScaleY = 1F;
            modernThemeToggle18.ShadowBlur = 8F;
            modernThemeToggle18.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle18.ShadowOffsetX = 0F;
            modernThemeToggle18.ShadowOffsetY = 4F;
            modernThemeToggle18.ShadowOpacity = 0.5F;
            modernThemeToggle18.Size = new Size(56, 28);
            modernThemeToggle18.Style = Custom_Buttons.ToggleStyle.Style2_ThinTrack;
            modernThemeToggle18.TabIndex = 12;
            modernThemeToggle18.Text = "modernThemeToggle18";
            modernThemeToggle18.TextAlignment = StringAlignment.Center;
            modernThemeToggle18.TextColor = Color.Black;
            modernThemeToggle18.ThumbColorOff = Color.White;
            modernThemeToggle18.ThumbColorOn = Color.White;
            modernThemeToggle18.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle18.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle18.UseAcrylic = false;
            modernThemeToggle18.UseGradient = false;
            modernThemeToggle18.UseRipple = false;
            modernThemeToggle18.UseShadow = false;
            modernThemeToggle18.UseSkiaGraphics = false;
            modernThemeToggle18.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle18.WordWrap = false;
            // 
            // modernThemeToggle19
            // 
            modernThemeToggle19.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle19.AnimationSpeed = 150F;
            modernThemeToggle19.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle19.BackColor = Color.Transparent;
            modernThemeToggle19.BackgroundColor = Color.Transparent;
            modernThemeToggle19.BackgroundColor2 = Color.Transparent;
            modernThemeToggle19.BackgroundImg = null;
            modernThemeToggle19.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle19.BorderColor = Color.Transparent;
            modernThemeToggle19.BorderRadius = 14F;
            modernThemeToggle19.BorderThickness = 0F;
            modernThemeToggle19.CheckedColor = Color.Transparent;
            modernThemeToggle19.CheckedColor2 = Color.Transparent;
            modernThemeToggle19.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle19.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle19.EnableHover = true;
            modernThemeToggle19.EnablePressEffect = true;
            modernThemeToggle19.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle19.FocusThickness = 0F;
            modernThemeToggle19.FontFamily = "Segoe UI";
            modernThemeToggle19.FontSize = 12F;
            modernThemeToggle19.FontWeightBold = false;
            modernThemeToggle19.HoverColor = Color.Transparent;
            modernThemeToggle19.HoverColor2 = Color.Transparent;
            modernThemeToggle19.ImageOpacity = 1F;
            modernThemeToggle19.Location = new Point(227, 313);
            modernThemeToggle19.MinimumSize = new Size(45, 22);
            modernThemeToggle19.Name = "modernThemeToggle19";
            modernThemeToggle19.Opacity = 1F;
            modernThemeToggle19.PressColor = Color.Transparent;
            modernThemeToggle19.PressColor2 = Color.Transparent;
            modernThemeToggle19.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle19.Rotation = 0F;
            modernThemeToggle19.ScaleX = 1F;
            modernThemeToggle19.ScaleY = 1F;
            modernThemeToggle19.ShadowBlur = 8F;
            modernThemeToggle19.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle19.ShadowOffsetX = 0F;
            modernThemeToggle19.ShadowOffsetY = 4F;
            modernThemeToggle19.ShadowOpacity = 0.5F;
            modernThemeToggle19.Size = new Size(56, 28);
            modernThemeToggle19.Style = Custom_Buttons.ToggleStyle.Style2_ThinTrack;
            modernThemeToggle19.TabIndex = 11;
            modernThemeToggle19.Text = "modernThemeToggle19";
            modernThemeToggle19.TextAlignment = StringAlignment.Center;
            modernThemeToggle19.TextColor = Color.Black;
            modernThemeToggle19.ThumbColorOff = Color.White;
            modernThemeToggle19.ThumbColorOn = Color.White;
            modernThemeToggle19.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle19.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle19.UseAcrylic = false;
            modernThemeToggle19.UseGradient = false;
            modernThemeToggle19.UseRipple = false;
            modernThemeToggle19.UseShadow = false;
            modernThemeToggle19.UseSkiaGraphics = true;
            modernThemeToggle19.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle19.WordWrap = false;
            // 
            // modernThemeToggle20
            // 
            modernThemeToggle20.AcrylicTintColor = Color.FromArgb(40, 255, 255, 255);
            modernThemeToggle20.AnimationSpeed = 150F;
            modernThemeToggle20.AnimationType = Core.AnimationEasing.Linear;
            modernThemeToggle20.BackColor = Color.Transparent;
            modernThemeToggle20.BackgroundColor = Color.Transparent;
            modernThemeToggle20.BackgroundColor2 = Color.Transparent;
            modernThemeToggle20.BackgroundImg = null;
            modernThemeToggle20.BackgroundImgLayout = ImageLayout.Zoom;
            modernThemeToggle20.BorderColor = Color.Transparent;
            modernThemeToggle20.BorderRadius = 14F;
            modernThemeToggle20.BorderThickness = 0F;
            modernThemeToggle20.CheckedColor = Color.Transparent;
            modernThemeToggle20.CheckedColor2 = Color.Transparent;
            modernThemeToggle20.DisabledColor = Color.FromArgb(200, 200, 200);
            modernThemeToggle20.DisabledTextColor = Color.FromArgb(130, 130, 130);
            modernThemeToggle20.EnableHover = true;
            modernThemeToggle20.EnablePressEffect = true;
            modernThemeToggle20.FocusColor = Color.FromArgb(0, 120, 215);
            modernThemeToggle20.FocusThickness = 0F;
            modernThemeToggle20.FontFamily = "Segoe UI";
            modernThemeToggle20.FontSize = 12F;
            modernThemeToggle20.FontWeightBold = false;
            modernThemeToggle20.HoverColor = Color.Transparent;
            modernThemeToggle20.HoverColor2 = Color.Transparent;
            modernThemeToggle20.ImageOpacity = 1F;
            modernThemeToggle20.Location = new Point(349, 265);
            modernThemeToggle20.MinimumSize = new Size(45, 22);
            modernThemeToggle20.Name = "modernThemeToggle20";
            modernThemeToggle20.Opacity = 1F;
            modernThemeToggle20.PressColor = Color.Transparent;
            modernThemeToggle20.PressColor2 = Color.Transparent;
            modernThemeToggle20.RippleColor = Color.FromArgb(60, 0, 0, 0);
            modernThemeToggle20.Rotation = 0F;
            modernThemeToggle20.ScaleX = 1F;
            modernThemeToggle20.ScaleY = 1F;
            modernThemeToggle20.ShadowBlur = 8F;
            modernThemeToggle20.ShadowColor = Color.FromArgb(50, 0, 0, 0);
            modernThemeToggle20.ShadowOffsetX = 0F;
            modernThemeToggle20.ShadowOffsetY = 4F;
            modernThemeToggle20.ShadowOpacity = 0.5F;
            modernThemeToggle20.Size = new Size(56, 28);
            modernThemeToggle20.Style = Custom_Buttons.ToggleStyle.Style3_LineTrack;
            modernThemeToggle20.TabIndex = 10;
            modernThemeToggle20.Text = "modernThemeToggle20";
            modernThemeToggle20.TextAlignment = StringAlignment.Center;
            modernThemeToggle20.TextColor = Color.Black;
            modernThemeToggle20.ThumbColorOff = Color.White;
            modernThemeToggle20.ThumbColorOn = Color.White;
            modernThemeToggle20.ToggleColorOff = Color.FromArgb(220, 224, 232);
            modernThemeToggle20.ToggleColorOn = Color.FromArgb(138, 43, 226);
            modernThemeToggle20.UseAcrylic = false;
            modernThemeToggle20.UseGradient = false;
            modernThemeToggle20.UseRipple = false;
            modernThemeToggle20.UseShadow = false;
            modernThemeToggle20.UseSkiaGraphics = false;
            modernThemeToggle20.VerticalAlignment = StringAlignment.Center;
            modernThemeToggle20.WordWrap = false;
            // 
            // Form1
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.LightSeaGreen;
            ClientSize = new Size(800, 450);
            Controls.Add(modernThemeToggle11);
            Controls.Add(modernThemeToggle12);
            Controls.Add(modernThemeToggle13);
            Controls.Add(modernThemeToggle14);
            Controls.Add(modernThemeToggle15);
            Controls.Add(modernThemeToggle16);
            Controls.Add(modernThemeToggle17);
            Controls.Add(modernThemeToggle18);
            Controls.Add(modernThemeToggle19);
            Controls.Add(modernThemeToggle20);
            Controls.Add(modernThemeToggle10);
            Controls.Add(modernThemeToggle8);
            Controls.Add(modernThemeToggle9);
            Controls.Add(modernThemeToggle6);
            Controls.Add(modernThemeToggle7);
            Controls.Add(modernThemeToggle4);
            Controls.Add(modernThemeToggle5);
            Controls.Add(modernThemeToggle3);
            Controls.Add(modernThemeToggle2);
            Controls.Add(modernThemeToggle1);
            DoubleBuffered = true;
            FormBorderStyle = FormBorderStyle.None;
            Name = "Form1";
            Text = "Form1";
            ResumeLayout(false);
        }

        #endregion

        private Core.ModernFormManager modernFormManager1;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle1;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle2;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle3;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle10;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle8;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle9;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle6;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle7;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle4;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle5;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle11;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle12;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle13;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle14;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle15;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle16;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle17;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle18;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle19;
        private Custom_Buttons.ModernThemeToggle modernThemeToggle20;
    }
}
